### Load Hmisc library
library(Hmisc)

#Setting Units

#Setting Factors(will create new variable for factors)
data$redcap_event_name = factor(data$redcap_event_name,levels=c("cadastro_do_hospit_arm_1","informaes_do_pacie_arm_2"))
data$redcap_repeat_instrument = factor(data$redcap_repeat_instrument,levels=c("dados_dirios_716778"))
data$redcap_data_access_group = factor(data$redcap_data_access_group,levels=c("hc__fmusp","hc__fmusp_ribeiro","hospital_albert_ei","hospital_beneficnc","hospital_da_luz__a","hospital_do_cncer","hospital_do_corao","hospital_e_materni","hospital_nereu_ram","hospital_paulistan","hospital_so_paulo","hospital_so_vicent","instituto_de_cardi","santa_casa_de_port"))
data$id_complete = factor(data$id_complete,levels=c("0","1","2"))
data$leitocup_ch = factor(data$leitocup_ch,levels=c("1","2"))
data$regihosp_ch = factor(data$regihosp_ch,levels=c("1","2","3"))
data$hospuni_ch = factor(data$hospuni_ch,levels=c("1","0"))
data$acredtac_ch = factor(data$acredtac_ch,levels=c("1","2","3","4","5","6","7"))
data$prontsoc_ch = factor(data$prontsoc_ch,levels=c("1","2","3"))
data$timeresp_ch = factor(data$timeresp_ch,levels=c("1","0"))
data$pgsepse_ch = factor(data$pgsepse_ch,levels=c("1","0"))
data$pgseda_ch = factor(data$pgseda_ch,levels=c("1","0"))
data$pginfar_ch = factor(data$pginfar_ch,levels=c("1","0"))
data$pgventi_ch = factor(data$pgventi_ch,levels=c("1","0"))
data$pgavc_ch = factor(data$pgavc_ch,levels=c("1","0"))
data$pgoutro_ch = factor(data$pgoutro_ch,levels=c("1","0"))
data$uti_ch = factor(data$uti_ch,levels=c("1","0"))
data$filauti_ch = factor(data$filauti_ch,levels=c("1","0"))
data$filautis_ch = factor(data$filautis_ch,levels=c("1","2"))
data$caracterizao_do_hospital_complete = factor(data$caracterizao_do_hospital_complete,levels=c("0","1","2"))
data$sexo_ad = factor(data$sexo_ad,levels=c("0","1"))
data$cepmorad_ad = factor(data$cepmorad_ad,levels=c("1","2","3"))
data$motivo_ad = factor(data$motivo_ad,levels=c("1","2","3"))
data$tipo_ad = factor(data$tipo_ad,levels=c("1","2"))
data$ciruresp_ad = factor(data$ciruresp_ad,levels=c("1","2","3","4","5","6"))
data$atb_ad = factor(data$atb_ad,levels=c("1","0"))
data$infec_ad = factor(data$infec_ad,levels=c("1","0"))
data$qfocinf_ad = factor(data$qfocinf_ad,levels=c("1","2","3","4","5","6","7","8","9","10","11","12"))
data$trauma_ad = factor(data$trauma_ad,levels=c("1","0"))
data$complpop_ad = factor(data$complpop_ad,levels=c("1","0"))
data$doeresp_ad = factor(data$doeresp_ad,levels=c("1","0"))
data$qdoeresp_ad___1 = factor(data$qdoeresp_ad___1,levels=c("0","1"))
data$qdoeresp_ad___2 = factor(data$qdoeresp_ad___2,levels=c("0","1"))
data$qdoeresp_ad___3 = factor(data$qdoeresp_ad___3,levels=c("0","1"))
data$doereum_ad = factor(data$doereum_ad,levels=c("1","0"))
data$doecoroi_ad = factor(data$doecoroi_ad,levels=c("1","0"))
data$doecoesp_ad = factor(data$doecoesp_ad,levels=c("1","2","3","4"))
data$icdescom_ad = factor(data$icdescom_ad,levels=c("1","0"))
data$tvp_ad = factor(data$tvp_ad,levels=c("1","0"))
data$tep_ad = factor(data$tep_ad,levels=c("1","0"))
data$doeneur_ad = factor(data$doeneur_ad,levels=c("1","0"))
data$dneuesp_ad = factor(data$dneuesp_ad,levels=c("1","2","3","4","5"))
data$irenal_ad = factor(data$irenal_ad,levels=c("1","0"))
data$irenaesp_ad = factor(data$irenaesp_ad,levels=c("1","2","3"))
data$cirroseh_ad = factor(data$cirroseh_ad,levels=c("1","0"))
data$cirrespe_ad = factor(data$cirrespe_ad,levels=c("1","2","3","4"))
data$pancreat_ad = factor(data$pancreat_ad,levels=c("1","0"))
data$dmdescom_ad = factor(data$dmdescom_ad,levels=c("1","0"))
data$invdiagn_ad = factor(data$invdiagn_ad,levels=c("1","0"))
data$outras_ad = factor(data$outras_ad,levels=c("1","0"))
data$dreumat_ad = factor(data$dreumat_ad,levels=c("1","0"))
data$dm_ad = factor(data$dm_ad,levels=c("1","0"))
data$dm_compl_ad = factor(data$dm_compl_ad,levels=c("1","0"))
data$tabag_ad = factor(data$tabag_ad,levels=c("0","1","2"))
data$dpoc_ad = factor(data$dpoc_ad,levels=c("1","0"))
data$pneumoni_ad = factor(data$pneumoni_ad,levels=c("1","0"))
data$infartmi_ad = factor(data$infartmi_ad,levels=c("1","0"))
data$angstent_ad = factor(data$angstent_ad,levels=c("1","0"))
data$has_ad = factor(data$has_ad,levels=c("1","0"))
data$epconfme_ad = factor(data$epconfme_ad,levels=c("1","0"))
data$interna_ad = factor(data$interna_ad,levels=c("1","0"))
data$demencia_ad = factor(data$demencia_ad,levels=c("1","0"))
data$homecare_ad = factor(data$homecare_ad,levels=c("1","0"))
data$ait_ad = factor(data$ait_ad,levels=c("1","0"))
data$aitseque_ad = factor(data$aitseque_ad,levels=c("1","0"))
data$avc_ad = factor(data$avc_ad,levels=c("1","0"))
data$avcseque_ad = factor(data$avcseque_ad,levels=c("1","0"))
data$ic_ad = factor(data$ic_ad,levels=c("1","0"))
data$icclassf_ad = factor(data$icclassf_ad,levels=c("1","2","3","4"))
data$dvascper_ad = factor(data$dvascper_ad,levels=c("1","0"))
data$atbasvid_ad = factor(data$atbasvid_ad,levels=c("1","0"))
data$sidaaids_ad = factor(data$sidaaids_ad,levels=c("1","0"))
data$cirrhepa_ad = factor(data$cirrhepa_ad,levels=c("1","0"))
data$child_ad = factor(data$child_ad,levels=c("1","2","3"))
data$neoplasi_ad = factor(data$neoplasi_ad,levels=c("1","0"))
data$neoptipo_ad = factor(data$neoptipo_ad,levels=c("1","2","3"))
data$transpmo_ad = factor(data$transpmo_ad,levels=c("1","0"))
data$admisso_complete = factor(data$admisso_complete,levels=c("0","1","2"))
data$locpaci_dd = factor(data$locpaci_dd,levels=c("1","2","3"))
data$consienc_dd = factor(data$consienc_dd,levels=c("1","2","3","4","5","6"))
data$examlab = factor(data$examlab,levels=c("1","0"))
data$leuco_dd = factor(data$leuco_dd,levels=c("0","1"))
data$plaq_dd = factor(data$plaq_dd,levels=c("0","1"))
data$creat_dd = factor(data$creat_dd,levels=c("0","1"))
data$bilirr_dd = factor(data$bilirr_dd,levels=c("0","1"))
data$exlacta_dd = factor(data$exlacta_dd,levels=c("0","1"))
data$inrttpa_dd = factor(data$inrttpa_dd,levels=c("9","1","0"))
data$expvolem_dd = factor(data$expvolem_dd,levels=c("1","0"))
data$diagseps_dd = factor(data$diagseps_dd,levels=c("1","0"))
data$supoxi_dd = factor(data$supoxi_dd,levels=c("1","0"))
data$supvm_dd = factor(data$supvm_dd,levels=c("1","0"))
data$supvaso_dd = factor(data$supvaso_dd,levels=c("1","2","0"))
data$dosenora_dd = factor(data$dosenora_dd,levels=c("1","2","3"))
data$supsubre_dd = factor(data$supsubre_dd,levels=c("1","0"))
data$atbhoje_dd = factor(data$atbhoje_dd,levels=c("1","2","3"))
data$qcausa_dd = factor(data$qcausa_dd,levels=c("1","2","3","4","5"))
data$evavc_dd = factor(data$evavc_dd,levels=c("1","0"))
data$eviam_dd = factor(data$eviam_dd,levels=c("1","0"))
data$evceleti_dd = factor(data$evceleti_dd,levels=c("1","0"))
data$evcemer_dd = factor(data$evcemer_dd,levels=c("1","0"))
data$evcriseh_dd = factor(data$evcriseh_dd,levels=c("1","0"))
data$evqueda_dd = factor(data$evqueda_dd,levels=c("1","0"))
data$evarrit_dd = factor(data$evarrit_dd,levels=c("1","0"))
data$evconv_dd = factor(data$evconv_dd,levels=c("1","0"))
data$evtromb_dd = factor(data$evtromb_dd,levels=c("1","0"))
data$evbronco_dd = factor(data$evbronco_dd,levels=c("1","0"))
data$evhemor_dd = factor(data$evhemor_dd,levels=c("1","0"))
data$evpc_dd = factor(data$evpc_dd,levels=c("1","0"))
data$evdor_dd = factor(data$evdor_dd,levels=c("1","0"))
data$evuti_dd = factor(data$evuti_dd,levels=c("1","0"))
data$evoutro_dd = factor(data$evoutro_dd,levels=c("1","0"))
data$atbuso1_dd = factor(data$atbuso1_dd,levels=c("1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49"))
data$atbuso2_dd = factor(data$atbuso2_dd,levels=c("1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49"))
data$atbuso3_dd = factor(data$atbuso3_dd,levels=c("1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49"))
data$atbuso4_dd = factor(data$atbuso4_dd,levels=c("1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36","37","38","39","40","41","42","43","44","45","46","47","48","49"))
data$qfocinf_dd = factor(data$qfocinf_dd,levels=c("1","2","3","4","5","6","7","8","9","10","11","12"))
data$focompl_dd = factor(data$focompl_dd,levels=c("1","0"))
data$contfoco_dd = factor(data$contfoco_dd,levels=c("1","0"))
data$foco24h_dd = factor(data$foco24h_dd,levels=c("1","0"))
data$colcult_dd = factor(data$colcult_dd,levels=c("1","0"))
data$colhemop_dd = factor(data$colhemop_dd,levels=c("1","0"))
data$hpp1_dd = factor(data$hpp1_dd,levels=c("1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36"))
data$hpp1s1_dd___1 = factor(data$hpp1s1_dd___1,levels=c("0","1"))
data$hpp1s1_dd___2 = factor(data$hpp1s1_dd___2,levels=c("0","1"))
data$hpp1s1_dd___3 = factor(data$hpp1s1_dd___3,levels=c("0","1"))
data$hpp1s2_dd___2 = factor(data$hpp1s2_dd___2,levels=c("0","1"))
data$hpp1s2_dd___3 = factor(data$hpp1s2_dd___3,levels=c("0","1"))
data$hpp1s3_dd___1 = factor(data$hpp1s3_dd___1,levels=c("0","1"))
data$hpp1s3_dd___2 = factor(data$hpp1s3_dd___2,levels=c("0","1"))
data$hpp1s3_dd___3 = factor(data$hpp1s3_dd___3,levels=c("0","1"))
data$hpp1s3_dd___4 = factor(data$hpp1s3_dd___4,levels=c("0","1"))
data$hpp2_dd = factor(data$hpp2_dd,levels=c("1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36"))
data$hpp2s1_dd___1 = factor(data$hpp2s1_dd___1,levels=c("0","1"))
data$hpp2s1_dd___2 = factor(data$hpp2s1_dd___2,levels=c("0","1"))
data$hpp2s1_dd___3 = factor(data$hpp2s1_dd___3,levels=c("0","1"))
data$hpp2s2_dd___2 = factor(data$hpp2s2_dd___2,levels=c("0","1"))
data$hpp2s2_dd___3 = factor(data$hpp2s2_dd___3,levels=c("0","1"))
data$hpp2s3_dd___1 = factor(data$hpp2s3_dd___1,levels=c("0","1"))
data$hpp2s3_dd___2 = factor(data$hpp2s3_dd___2,levels=c("0","1"))
data$hpp2s3_dd___3 = factor(data$hpp2s3_dd___3,levels=c("0","1"))
data$hpp2s3_dd___4 = factor(data$hpp2s3_dd___4,levels=c("0","1"))
data$coltraq_dd = factor(data$coltraq_dd,levels=c("1","0"))
data$stp1_dd = factor(data$stp1_dd,levels=c("1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36"))
data$stp1s1_dd___1 = factor(data$stp1s1_dd___1,levels=c("0","1"))
data$stp1s1_dd___2 = factor(data$stp1s1_dd___2,levels=c("0","1"))
data$stp1s1_dd___3 = factor(data$stp1s1_dd___3,levels=c("0","1"))
data$stp1s2_dd___2 = factor(data$stp1s2_dd___2,levels=c("0","1"))
data$stp1s2_dd___3 = factor(data$stp1s2_dd___3,levels=c("0","1"))
data$stp1s3_dd___1 = factor(data$stp1s3_dd___1,levels=c("0","1"))
data$stp1s3_dd___2 = factor(data$stp1s3_dd___2,levels=c("0","1"))
data$stp1s3_dd___3 = factor(data$stp1s3_dd___3,levels=c("0","1"))
data$stp1s3_dd___4 = factor(data$stp1s3_dd___4,levels=c("0","1"))
data$stp2_dd = factor(data$stp2_dd,levels=c("1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36"))
data$stp2s1_dd___1 = factor(data$stp2s1_dd___1,levels=c("0","1"))
data$stp2s1_dd___2 = factor(data$stp2s1_dd___2,levels=c("0","1"))
data$stp2s1_dd___3 = factor(data$stp2s1_dd___3,levels=c("0","1"))
data$stp2s2_dd___2 = factor(data$stp2s2_dd___2,levels=c("0","1"))
data$stp2s2_dd___3 = factor(data$stp2s2_dd___3,levels=c("0","1"))
data$stp2s3_dd___1 = factor(data$stp2s3_dd___1,levels=c("0","1"))
data$stp2s3_dd___2 = factor(data$stp2s3_dd___2,levels=c("0","1"))
data$stp2s3_dd___3 = factor(data$stp2s3_dd___3,levels=c("0","1"))
data$stp2s3_dd___4 = factor(data$stp2s3_dd___4,levels=c("0","1"))
data$colurina_dd = factor(data$colurina_dd,levels=c("1","0"))
data$urp1_dd = factor(data$urp1_dd,levels=c("1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36"))
data$urp1s1_dd___1 = factor(data$urp1s1_dd___1,levels=c("0","1"))
data$urp1s1_dd___2 = factor(data$urp1s1_dd___2,levels=c("0","1"))
data$urp1s1_dd___3 = factor(data$urp1s1_dd___3,levels=c("0","1"))
data$urp1s2_dd___2 = factor(data$urp1s2_dd___2,levels=c("0","1"))
data$urp1s2_dd___3 = factor(data$urp1s2_dd___3,levels=c("0","1"))
data$urp1s3_dd___1 = factor(data$urp1s3_dd___1,levels=c("0","1"))
data$urp1s3_dd___2 = factor(data$urp1s3_dd___2,levels=c("0","1"))
data$urp1s3_dd___3 = factor(data$urp1s3_dd___3,levels=c("0","1"))
data$urp1s3_dd___4 = factor(data$urp1s3_dd___4,levels=c("0","1"))
data$urp2_dd = factor(data$urp2_dd,levels=c("1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36"))
data$urp2s1_dd___1 = factor(data$urp2s1_dd___1,levels=c("0","1"))
data$urp2s1_dd___2 = factor(data$urp2s1_dd___2,levels=c("0","1"))
data$urp2s1_dd___3 = factor(data$urp2s1_dd___3,levels=c("0","1"))
data$urp2s2_dd___2 = factor(data$urp2s2_dd___2,levels=c("0","1"))
data$urp2s2_dd___3 = factor(data$urp2s2_dd___3,levels=c("0","1"))
data$urp2s3_dd___1 = factor(data$urp2s3_dd___1,levels=c("0","1"))
data$urp2s3_dd___2 = factor(data$urp2s3_dd___2,levels=c("0","1"))
data$urp2s3_dd___3 = factor(data$urp2s3_dd___3,levels=c("0","1"))
data$urp2s3_dd___4 = factor(data$urp2s3_dd___4,levels=c("0","1"))
data$colcatet_dd = factor(data$colcatet_dd,levels=c("1","0"))
data$pcp1_dd = factor(data$pcp1_dd,levels=c("1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36"))
data$pcp1s1_dd___1 = factor(data$pcp1s1_dd___1,levels=c("0","1"))
data$pcp1s1_dd___2 = factor(data$pcp1s1_dd___2,levels=c("0","1"))
data$pcp1s1_dd___3 = factor(data$pcp1s1_dd___3,levels=c("0","1"))
data$pcp1s2_dd___2 = factor(data$pcp1s2_dd___2,levels=c("0","1"))
data$pcp1s2_dd___3 = factor(data$pcp1s2_dd___3,levels=c("0","1"))
data$pcp1s3_dd___1 = factor(data$pcp1s3_dd___1,levels=c("0","1"))
data$pcp1s3_dd___2 = factor(data$pcp1s3_dd___2,levels=c("0","1"))
data$pcp1s3_dd___3 = factor(data$pcp1s3_dd___3,levels=c("0","1"))
data$pcp1s3_dd___4 = factor(data$pcp1s3_dd___4,levels=c("0","1"))
data$pcp2_dd = factor(data$pcp2_dd,levels=c("1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36"))
data$pcp2s1_dd___1 = factor(data$pcp2s1_dd___1,levels=c("0","1"))
data$pcp2s1_dd___2 = factor(data$pcp2s1_dd___2,levels=c("0","1"))
data$pcp2s1_dd___3 = factor(data$pcp2s1_dd___3,levels=c("0","1"))
data$pcp2s2_dd___2 = factor(data$pcp2s2_dd___2,levels=c("0","1"))
data$pcp2s2_dd___3 = factor(data$pcp2s2_dd___3,levels=c("0","1"))
data$pcp2s3_dd___1 = factor(data$pcp2s3_dd___1,levels=c("0","1"))
data$pcp2s3_dd___2 = factor(data$pcp2s3_dd___2,levels=c("0","1"))
data$pcp2s3_dd___3 = factor(data$pcp2s3_dd___3,levels=c("0","1"))
data$pcp2s3_dd___4 = factor(data$pcp2s3_dd___4,levels=c("0","1"))
data$colbronco_dd = factor(data$colbronco_dd,levels=c("1","0"))
data$lbp1_dd = factor(data$lbp1_dd,levels=c("1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36"))
data$lbp1s1_dd___1 = factor(data$lbp1s1_dd___1,levels=c("0","1"))
data$lbp1s1_dd___2 = factor(data$lbp1s1_dd___2,levels=c("0","1"))
data$lbp1s1_dd___3 = factor(data$lbp1s1_dd___3,levels=c("0","1"))
data$lbp1s2_dd___2 = factor(data$lbp1s2_dd___2,levels=c("0","1"))
data$lbp1s2_dd___3 = factor(data$lbp1s2_dd___3,levels=c("0","1"))
data$lbp1s3_dd___1 = factor(data$lbp1s3_dd___1,levels=c("0","1"))
data$lbp1s3_dd___2 = factor(data$lbp1s3_dd___2,levels=c("0","1"))
data$lbp1s3_dd___3 = factor(data$lbp1s3_dd___3,levels=c("0","1"))
data$lbp1s3_dd___4 = factor(data$lbp1s3_dd___4,levels=c("0","1"))
data$lbp2_dd = factor(data$lbp2_dd,levels=c("1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36"))
data$lbp2s1_dd___1 = factor(data$lbp2s1_dd___1,levels=c("0","1"))
data$lbp2s1_dd___2 = factor(data$lbp2s1_dd___2,levels=c("0","1"))
data$lbp2s1_dd___3 = factor(data$lbp2s1_dd___3,levels=c("0","1"))
data$lbp2s2_dd___2 = factor(data$lbp2s2_dd___2,levels=c("0","1"))
data$lbp2s2_dd___3 = factor(data$lbp2s2_dd___3,levels=c("0","1"))
data$lbp2s3_dd___1 = factor(data$lbp2s3_dd___1,levels=c("0","1"))
data$lbp2s3_dd___2 = factor(data$lbp2s3_dd___2,levels=c("0","1"))
data$lbp2s3_dd___3 = factor(data$lbp2s3_dd___3,levels=c("0","1"))
data$lbp2s3_dd___4 = factor(data$lbp2s3_dd___4,levels=c("0","1"))
data$colhemoc_dd = factor(data$colhemoc_dd,levels=c("1","0"))
data$hcp1_dd = factor(data$hcp1_dd,levels=c("1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36"))
data$hcp1s1_dd___1 = factor(data$hcp1s1_dd___1,levels=c("0","1"))
data$hcp1s1_dd___2 = factor(data$hcp1s1_dd___2,levels=c("0","1"))
data$hcp1s1_dd___3 = factor(data$hcp1s1_dd___3,levels=c("0","1"))
data$hcp1s2_dd___2 = factor(data$hcp1s2_dd___2,levels=c("0","1"))
data$hcp1s2_dd___3 = factor(data$hcp1s2_dd___3,levels=c("0","1"))
data$hcp1s3_dd___1 = factor(data$hcp1s3_dd___1,levels=c("0","1"))
data$hcp1s3_dd___2 = factor(data$hcp1s3_dd___2,levels=c("0","1"))
data$hcp1s3_dd___3 = factor(data$hcp1s3_dd___3,levels=c("0","1"))
data$hcp1s3_dd___4 = factor(data$hcp1s3_dd___4,levels=c("0","1"))
data$hcp2_dd = factor(data$hcp2_dd,levels=c("1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36"))
data$hcp2s1_dd___1 = factor(data$hcp2s1_dd___1,levels=c("0","1"))
data$hcp2s1_dd___2 = factor(data$hcp2s1_dd___2,levels=c("0","1"))
data$hcp2s1_dd___3 = factor(data$hcp2s1_dd___3,levels=c("0","1"))
data$hcp2s2_dd___2 = factor(data$hcp2s2_dd___2,levels=c("0","1"))
data$hcp2s2_dd___3 = factor(data$hcp2s2_dd___3,levels=c("0","1"))
data$hcp2s3_dd___1 = factor(data$hcp2s3_dd___1,levels=c("0","1"))
data$hcp2s3_dd___2 = factor(data$hcp2s3_dd___2,levels=c("0","1"))
data$hcp2s3_dd___3 = factor(data$hcp2s3_dd___3,levels=c("0","1"))
data$hcp2s3_dd___4 = factor(data$hcp2s3_dd___4,levels=c("0","1"))
data$colpunc_dd = factor(data$colpunc_dd,levels=c("1","0"))
data$plp1_dd = factor(data$plp1_dd,levels=c("1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36"))
data$plp1s1_dd___1 = factor(data$plp1s1_dd___1,levels=c("0","1"))
data$plp1s1_dd___2 = factor(data$plp1s1_dd___2,levels=c("0","1"))
data$plp1s1_dd___3 = factor(data$plp1s1_dd___3,levels=c("0","1"))
data$plp1s2_dd___2 = factor(data$plp1s2_dd___2,levels=c("0","1"))
data$plp1s2_dd___3 = factor(data$plp1s2_dd___3,levels=c("0","1"))
data$plp1s3_dd___1 = factor(data$plp1s3_dd___1,levels=c("0","1"))
data$plp1s3_dd___2 = factor(data$plp1s3_dd___2,levels=c("0","1"))
data$plp1s3_dd___3 = factor(data$plp1s3_dd___3,levels=c("0","1"))
data$plp1s3_dd___4 = factor(data$plp1s3_dd___4,levels=c("0","1"))
data$plp2_dd = factor(data$plp2_dd,levels=c("1","2","3","4","5","6","7","8","9","10","11","12","13","14","15","16","17","18","19","20","21","22","23","24","25","26","27","28","29","30","31","32","33","34","35","36"))
data$plp2s1_dd___1 = factor(data$plp2s1_dd___1,levels=c("0","1"))
data$plp2s1_dd___2 = factor(data$plp2s1_dd___2,levels=c("0","1"))
data$plp2s1_dd___3 = factor(data$plp2s1_dd___3,levels=c("0","1"))
data$plp2s2_dd___2 = factor(data$plp2s2_dd___2,levels=c("0","1"))
data$plp2s2_dd___3 = factor(data$plp2s2_dd___3,levels=c("0","1"))
data$plp2s3_dd___1 = factor(data$plp2s3_dd___1,levels=c("0","1"))
data$plp2s3_dd___2 = factor(data$plp2s3_dd___2,levels=c("0","1"))
data$plp2s3_dd___3 = factor(data$plp2s3_dd___3,levels=c("0","1"))
data$plp2s3_dd___4 = factor(data$plp2s3_dd___4,levels=c("0","1"))
data$dados_dirios_716778_complete = factor(data$dados_dirios_716778_complete,levels=c("0","1","2"))
data$statalta_ah = factor(data$statalta_ah,levels=c("0","1"))
data$alta_ah = factor(data$alta_ah,levels=c("1","2","3","4"))
data$limressu_ah = factor(data$limressu_ah,levels=c("1","0"))
data$limadsu_ah = factor(data$limadsu_ah,levels=c("1","0"))
data$limretsu_ah = factor(data$limretsu_ah,levels=c("1","0"))
data$dcorpo_ah = factor(data$dcorpo_ah,levels=c("1","2","3"))
data$alta_hospitalar_complete = factor(data$alta_hospitalar_complete,levels=c("0","1","2"))

levels(data$redcap_event_name)=c("Cadastro do hospital (Arm 1: Hospitais)","Informações do paciente (Arm 2: Pacientes)")
levels(data$redcap_repeat_instrument)=c("Dados diários")
levels(data$redcap_data_access_group)=c("HC - FMUSP","HC - FMUSP Ribeirão Preto","Hospital Albert Einstein","Hospital Beneficência Portuguesa","Hospital da Luz - Amico Saúde LTDA","Hospital do Câncer - AC Camargo","Hospital do Coração - HCor","Hospital e Maternidade São Vicente de Paulo","Hospital Nereu Ramos","Hospital Paulistano","Hospital São Paulo - UNIFESP","Hospital São Vicente de Paulo Passo Fundo","Instituto de Cardiologia do Distrito Federal","Santa Casa de Porto Alegre")
levels(data$id_complete)=c("Incomplete","Unverified","Complete")
levels(data$leitocup_ch)=c("SUS","Saúde suplementar")
levels(data$regihosp_ch)=c("Público (Federal, Estadual ou Municipal)","Privado Filantrópico","Privado não filantrópico")
levels(data$hospuni_ch)=c("Sim","Não")
levels(data$acredtac_ch)=c("ONA I","ONA II","ONA III","JCI","Canadense","Outra","Nenhuma")
levels(data$prontsoc_ch)=c("Sem pronto-socorro","Referenciado","Aberto")
levels(data$timeresp_ch)=c("Sim","Não")
levels(data$pgsepse_ch)=c("Sim","Não")
levels(data$pgseda_ch)=c("Sim","Não")
levels(data$pginfar_ch)=c("Sim","Não")
levels(data$pgventi_ch)=c("Sim","Não")
levels(data$pgavc_ch)=c("Sim","Não")
levels(data$pgoutro_ch)=c("Sim","Não")
levels(data$uti_ch)=c("Sim","Não")
levels(data$filauti_ch)=c("Sim","Não")
levels(data$filautis_ch)=c("Até 2 vezes na semana","Mais de 2 vezes na semana")
levels(data$caracterizao_do_hospital_complete)=c("Incomplete","Unverified","Complete")
levels(data$sexo_ad)=c("Masculino","Feminino")
levels(data$cepmorad_ad)=c("Disponível (preencha o CEP de moradia)","Não disponível","Zona urbana não documentada")
levels(data$motivo_ad)=c("Clínica","Cirurgia eletiva","Cirurgia de Emergência/Trauma")
levels(data$tipo_ad)=c("Planejada","Não planejada")
levels(data$ciruresp_ad)=c("Neurológica","Ortopédica","Torácica","Abdominal","Vascular","Partes moles")
levels(data$atb_ad)=c("Sim","Não")
levels(data$infec_ad)=c("Sim","Não")
levels(data$qfocinf_ad)=c("Pneumonia/Empiema","Infecção urinária","Infecção abdominal aguda","Meningite","Endocardite","Pele/partes moles","Infecção de prótese","Infecção óssea/articular","Ferida operatória","Infecção de corrente sanguínea associada ao cateter","Sem foco definido","Outras infecções")
levels(data$trauma_ad)=c("Sim","Não")
levels(data$complpop_ad)=c("Sim","Não")
levels(data$doeresp_ad)=c("Sim","Não")
levels(data$qdoeresp_ad___1)=c("Unchecked","Checked")
levels(data$qdoeresp_ad___2)=c("Unchecked","Checked")
levels(data$qdoeresp_ad___3)=c("Unchecked","Checked")
levels(data$doereum_ad)=c("Sim","Não")
levels(data$doecoroi_ad)=c("Sim","Não")
levels(data$doecoesp_ad)=c("Infarto com supra ST","Infarto sem supra ST","Angina instável","Angina estável")
levels(data$icdescom_ad)=c("Sim","Não")
levels(data$tvp_ad)=c("Sim","Não")
levels(data$tep_ad)=c("Sim","Não")
levels(data$doeneur_ad)=c("Sim","Não")
levels(data$dneuesp_ad)=c("Acidente Vascular Cerebral Isquêmico (AVCi)","Acidente Vascular Cerebral hemorrágico (AVCh)","Ataque Isquêmico Transitório (AIT)","Hemorragia Subaracnóidea (HSA)","Polirradiculoneurite/Miastenia")
levels(data$irenal_ad)=c("Sim","Não")
levels(data$irenaesp_ad)=c("Aguda (não relacionada à cirrose)","Crônica (creatinina ≥ 2.0 mg/dL)","Crônica em diálise")
levels(data$cirroseh_ad)=c("Sim","Não")
levels(data$cirrespe_ad)=c("Cirrose descompensada","Hemorragia digestiva","Peritonite bacteriana espontânea","Síndrome hepatorenal")
levels(data$pancreat_ad)=c("Sim","Não")
levels(data$dmdescom_ad)=c("Sim","Não")
levels(data$invdiagn_ad)=c("Sim","Não")
levels(data$outras_ad)=c("Sim","Não")
levels(data$dreumat_ad)=c("Sim","Não")
levels(data$dm_ad)=c("Sim","Não")
levels(data$dm_compl_ad)=c("Sim","Não")
levels(data$tabag_ad)=c("Nunca fumou","Ex-fumante","Fumante atual")
levels(data$dpoc_ad)=c("Sim","Não")
levels(data$pneumoni_ad)=c("Sim","Não")
levels(data$infartmi_ad)=c("Sim","Não")
levels(data$angstent_ad)=c("Sim","Não")
levels(data$has_ad)=c("Sim","Não")
levels(data$epconfme_ad)=c("Sim","Não")
levels(data$interna_ad)=c("Sim","Não")
levels(data$demencia_ad)=c("Sim","Não")
levels(data$homecare_ad)=c("Sim","Não")
levels(data$ait_ad)=c("Sim","Não")
levels(data$aitseque_ad)=c("Sim","Não")
levels(data$avc_ad)=c("Sim","Não")
levels(data$avcseque_ad)=c("Sim","Não")
levels(data$ic_ad)=c("Sim","Não")
levels(data$icclassf_ad)=c("I","II","III","IV")
levels(data$dvascper_ad)=c("Sim","Não")
levels(data$atbasvid_ad)=c("Sim","Não")
levels(data$sidaaids_ad)=c("Sim","Não")
levels(data$cirrhepa_ad)=c("Sim","Não")
levels(data$child_ad)=c("A","B","C")
levels(data$neoplasi_ad)=c("Sim","Não")
levels(data$neoptipo_ad)=c("Sólida sem metástases","Sólida com metástases","Hematológica")
levels(data$transpmo_ad)=c("Sim","Não")
levels(data$admisso_complete)=c("Incomplete","Unverified","Complete")
levels(data$locpaci_dd)=c("Unidade de internação","Pronto socorro","UTI")
levels(data$consienc_dd)=c("15","13 -14","10 - 12","6 - 9","< 6","Não foi possível estimar")
levels(data$examlab)=c("Sim","Não")
levels(data$leuco_dd)=c("Não disponível","Disponível")
levels(data$plaq_dd)=c("Não disponível","Disponível")
levels(data$creat_dd)=c("Não disponível","Disponível")
levels(data$bilirr_dd)=c("Não disponível","Disponível")
levels(data$exlacta_dd)=c("Não disponível","Disponível")
levels(data$inrttpa_dd)=c("Não disponível","Sim","Não")
levels(data$expvolem_dd)=c("Sim","Não")
levels(data$diagseps_dd)=c("Sim","Não")
levels(data$supoxi_dd)=c("Sim","Não")
levels(data$supvm_dd)=c("Sim","Não")
levels(data$supvaso_dd)=c("Sim, início hoje","Sim, mesmo de ontem","Não")
levels(data$dosenora_dd)=c("< 0,1 mcg/Kg/min","0,1 a 0,3 mcg/Kg/min","> 0,3 mcg/Kg/min")
levels(data$supsubre_dd)=c("Sim","Não")
levels(data$atbhoje_dd)=c("Sim, adicionou novo","Sim, mesmo de antes","Não")
levels(data$qcausa_dd)=c("Descalonamento","Readequação para espectro (p.ex. adição ou troca de antibiótico baseado em cultura)","Evento/adverso / efeito colateral","Piora clínica","Não definido em prontuário")
levels(data$evavc_dd)=c("Sim","Não")
levels(data$eviam_dd)=c("Sim","Não")
levels(data$evceleti_dd)=c("Sim","Não")
levels(data$evcemer_dd)=c("Sim","Não")
levels(data$evcriseh_dd)=c("Sim","Não")
levels(data$evqueda_dd)=c("Sim","Não")
levels(data$evarrit_dd)=c("Sim","Não")
levels(data$evconv_dd)=c("Sim","Não")
levels(data$evtromb_dd)=c("Sim","Não")
levels(data$evbronco_dd)=c("Sim","Não")
levels(data$evhemor_dd)=c("Sim","Não")
levels(data$evpc_dd)=c("Sim","Não")
levels(data$evdor_dd)=c("Sim","Não")
levels(data$evuti_dd)=c("Sim","Não")
levels(data$evoutro_dd)=c("Sim","Não")
levels(data$atbuso1_dd)=c("Amicacina","Amoxicilina-clavulanato","Ampicilina","Ampicilina-sulbactam","Anfotericina B","Anidulafungina","Azitromicina","Caspofungina","Cefepime","Cefotaxima","Ceftarolina","Ceftazidima-avibactam","Ceftazidime","Ceftriaxona","Cefuroxima","Ciprofloxacina","Claritromicina","Clindamicina","Cloranfenicol","Daptomicina","Ertapenem","Fluconazol","Fosfomicina","Gatifloxacina","Gentamicina","Imipenem / Cilastin","Levofloxacina","Linezolida","Meropenem","Metronidazol","Micafungina","Moxifloxacina","Outra equinocandina","Outra quinolona","Outras sulfas","Outro aminoglicosídeo","Outro carbapenêmico","Outro macrolídeo","Piperacilina/Tazobactana","Polimixina B","Polimixina E","Sulfadiazina","Sulfametoxazol e tripetropim","Teicoplamina","Ticarcilina/clavulanato","Tigeciclina","Tobramicina","Vancomicina","Variconazol")
levels(data$atbuso2_dd)=c("Amicacina","Amoxicilina-clavulanato","Ampicilina","Ampicilina-sulbactam","Anfotericina B","Anidulafungina","Azitromicina","Caspofungina","Cefepime","Cefotaxima","Ceftarolina","Ceftazidima-avibactam","Ceftazidime","Ceftriaxona","Cefuroxima","Ciprofloxacina","Claritromicina","Clindamicina","Cloranfenicol","Daptomicina","Ertapenem","Fluconazol","Fosfomicina","Gatifloxacina","Gentamicina","Imipenem / Cilastin","Levofloxacina","Linezolida","Meropenem","Metronidazol","Micafungina","Moxifloxacina","Outra equinocandina","Outra quinolona","Outras sulfas","Outro aminoglicosídeo","Outro carbapenêmico","Outro macrolídeo","Piperacilina/Tazobactana","Polimixina B","Polimixina E","Sulfadiazina","Sulfametoxazol e tripetropim","Teicoplamina","Ticarcilina/clavulanato","Tigeciclina","Tobramicina","Vancomicina","Variconazol")
levels(data$atbuso3_dd)=c("Amicacina","Amoxicilina-clavulanato","Ampicilina","Ampicilina-sulbactam","Anfotericina B","Anidulafungina","Azitromicina","Caspofungina","Cefepime","Cefotaxima","Ceftarolina","Ceftazidima-avibactam","Ceftazidime","Ceftriaxona","Cefuroxima","Ciprofloxacina","Claritromicina","Clindamicina","Cloranfenicol","Daptomicina","Ertapenem","Fluconazol","Fosfomicina","Gatifloxacina","Gentamicina","Imipenem / Cilastin","Levofloxacina","Linezolida","Meropenem","Metronidazol","Micafungina","Moxifloxacina","Outra equinocandina","Outra quinolona","Outras sulfas","Outro aminoglicosídeo","Outro carbapenêmico","Outro macrolídeo","Piperacilina/Tazobactana","Polimixina B","Polimixina E","Sulfadiazina","Sulfametoxazol e tripetropim","Teicoplamina","Ticarcilina/clavulanato","Tigeciclina","Tobramicina","Vancomicina","Variconazol")
levels(data$atbuso4_dd)=c("Amicacina","Amoxicilina-clavulanato","Ampicilina","Ampicilina-sulbactam","Anfotericina B","Anidulafungina","Azitromicina","Caspofungina","Cefepime","Cefotaxima","Ceftarolina","Ceftazidima-avibactam","Ceftazidime","Ceftriaxona","Cefuroxima","Ciprofloxacina","Claritromicina","Clindamicina","Cloranfenicol","Daptomicina","Ertapenem","Fluconazol","Fosfomicina","Gatifloxacina","Gentamicina","Imipenem / Cilastin","Levofloxacina","Linezolida","Meropenem","Metronidazol","Micafungina","Moxifloxacina","Outra equinocandina","Outra quinolona","Outras sulfas","Outro aminoglicosídeo","Outro carbapenêmico","Outro macrolídeo","Piperacilina/Tazobactana","Polimixina B","Polimixina E","Sulfadiazina","Sulfametoxazol e tripetropim","Teicoplamina","Ticarcilina/clavulanato","Tigeciclina","Tobramicina","Vancomicina","Variconazol")
levels(data$qfocinf_dd)=c("Pneumonia/Empiema","Infecção urinária","Infecção abdominal aguda","Meningite","Endocardite","Pele/partes moles","Infecção de prótese","Infecção óssea/articular","Ferida operatória","Infecção de corrente sanguínea associada ao cateter","Sem foco definido","Outras infecções")
levels(data$focompl_dd)=c("Sim","Não")
levels(data$contfoco_dd)=c("Sim","Não")
levels(data$foco24h_dd)=c("Sim","Não")
levels(data$colcult_dd)=c("Sim","Não")
levels(data$colhemop_dd)=c("Sim","Não")
levels(data$hpp1_dd)=c("Acinetobacter baumannii","Acinetobacter sp","Aspergillus","Candida albicans","Candida glabrata","Candida kruzei","Candida sp","Clostridium SP","Enterococcus faecalis","Enterococcus faecium","Escherichia coli","Escherichia sp","Fusarium","Haemophilus influenzae","Haemophilus sp","Klebsiella oxytoca","Klebsiella pneumonia","Klebsiella sp","Listeria monocytogenes","Neisseria meningitidis","Outras leveduras","Outros bacilos gram positivos","Outros bacilos Gram-negativo","Outros cocos gram negativos","Outros cocos gram positivos","Outros Enterococcus","Outros fungos filamentosos","Outros patógenos","Outros Staphylococcus","Outros Streptococcus","Pneumocystis jirovecci","Pseudomonas aeruginosa","Pseudomonas sp","Staphylococcus aureus","Streptococcus pneumoniae","Nenhum")
levels(data$hpp1s1_dd___1)=c("Unchecked","Checked")
levels(data$hpp1s1_dd___2)=c("Unchecked","Checked")
levels(data$hpp1s1_dd___3)=c("Unchecked","Checked")
levels(data$hpp1s2_dd___2)=c("Unchecked","Checked")
levels(data$hpp1s2_dd___3)=c("Unchecked","Checked")
levels(data$hpp1s3_dd___1)=c("Unchecked","Checked")
levels(data$hpp1s3_dd___2)=c("Unchecked","Checked")
levels(data$hpp1s3_dd___3)=c("Unchecked","Checked")
levels(data$hpp1s3_dd___4)=c("Unchecked","Checked")
levels(data$hpp2_dd)=c("Acinetobacter baumannii","Acinetobacter sp","Aspergillus","Candida albicans","Candida glabrata","Candida kruzei","Candida sp","Clostridium SP","Enterococcus faecalis","Enterococcus faecium","Escherichia coli","Escherichia sp","Fusarium","Haemophilus influenzae","Haemophilus sp","Klebsiella oxytoca","Klebsiella pneumonia","Klebsiella sp","Listeria monocytogenes","Neisseria meningitidis","Outras leveduras","Outros bacilos gram positivos","Outros bacilos Gram-negativo","Outros cocos gram negativos","Outros cocos gram positivos","Outros Enterococcus","Outros fungos filamentosos","Outros patógenos","Outros Staphylococcus","Outros Streptococcus","Pneumocystis jirovecci","Pseudomonas aeruginosa","Pseudomonas sp","Staphylococcus aureus","Streptococcus pneumoniae","Nenhum")
levels(data$hpp2s1_dd___1)=c("Unchecked","Checked")
levels(data$hpp2s1_dd___2)=c("Unchecked","Checked")
levels(data$hpp2s1_dd___3)=c("Unchecked","Checked")
levels(data$hpp2s2_dd___2)=c("Unchecked","Checked")
levels(data$hpp2s2_dd___3)=c("Unchecked","Checked")
levels(data$hpp2s3_dd___1)=c("Unchecked","Checked")
levels(data$hpp2s3_dd___2)=c("Unchecked","Checked")
levels(data$hpp2s3_dd___3)=c("Unchecked","Checked")
levels(data$hpp2s3_dd___4)=c("Unchecked","Checked")
levels(data$coltraq_dd)=c("Sim","Não")
levels(data$stp1_dd)=c("Acinetobacter baumannii","Acinetobacter sp","Aspergillus","Candida albicans","Candida glabrata","Candida kruzei","Candida sp","Clostridium SP","Enterococcus faecalis","Enterococcus faecium","Escherichia coli","Escherichia sp","Fusarium","Haemophilus influenzae","Haemophilus sp","Klebsiella oxytoca","Klebsiella pneumonia","Klebsiella sp","Listeria monocytogenes","Neisseria meningitidis","Outras leveduras","Outros bacilos gram positivos","Outros bacilos Gram-negativo","Outros cocos gram negativos","Outros cocos gram positivos","Outros Enterococcus","Outros fungos filamentosos","Outros patógenos","Outros Staphylococcus","Outros Streptococcus","Pneumocystis jirovecci","Pseudomonas aeruginosa","Pseudomonas sp","Staphylococcus aureus","Streptococcus pneumoniae","Nenhum")
levels(data$stp1s1_dd___1)=c("Unchecked","Checked")
levels(data$stp1s1_dd___2)=c("Unchecked","Checked")
levels(data$stp1s1_dd___3)=c("Unchecked","Checked")
levels(data$stp1s2_dd___2)=c("Unchecked","Checked")
levels(data$stp1s2_dd___3)=c("Unchecked","Checked")
levels(data$stp1s3_dd___1)=c("Unchecked","Checked")
levels(data$stp1s3_dd___2)=c("Unchecked","Checked")
levels(data$stp1s3_dd___3)=c("Unchecked","Checked")
levels(data$stp1s3_dd___4)=c("Unchecked","Checked")
levels(data$stp2_dd)=c("Acinetobacter baumannii","Acinetobacter sp","Aspergillus","Candida albicans","Candida glabrata","Candida kruzei","Candida sp","Clostridium SP","Enterococcus faecalis","Enterococcus faecium","Escherichia coli","Escherichia sp","Fusarium","Haemophilus influenzae","Haemophilus sp","Klebsiella oxytoca","Klebsiella pneumonia","Klebsiella sp","Listeria monocytogenes","Neisseria meningitidis","Outras leveduras","Outros bacilos gram positivos","Outros bacilos Gram-negativo","Outros cocos gram negativos","Outros cocos gram positivos","Outros Enterococcus","Outros fungos filamentosos","Outros patógenos","Outros Staphylococcus","Outros Streptococcus","Pneumocystis jirovecci","Pseudomonas aeruginosa","Pseudomonas sp","Staphylococcus aureus","Streptococcus pneumoniae","Nenhum")
levels(data$stp2s1_dd___1)=c("Unchecked","Checked")
levels(data$stp2s1_dd___2)=c("Unchecked","Checked")
levels(data$stp2s1_dd___3)=c("Unchecked","Checked")
levels(data$stp2s2_dd___2)=c("Unchecked","Checked")
levels(data$stp2s2_dd___3)=c("Unchecked","Checked")
levels(data$stp2s3_dd___1)=c("Unchecked","Checked")
levels(data$stp2s3_dd___2)=c("Unchecked","Checked")
levels(data$stp2s3_dd___3)=c("Unchecked","Checked")
levels(data$stp2s3_dd___4)=c("Unchecked","Checked")
levels(data$colurina_dd)=c("Sim","Não")
levels(data$urp1_dd)=c("Acinetobacter baumannii","Acinetobacter sp","Aspergillus","Candida albicans","Candida glabrata","Candida kruzei","Candida sp","Clostridium SP","Enterococcus faecalis","Enterococcus faecium","Escherichia coli","Escherichia sp","Fusarium","Haemophilus influenzae","Haemophilus sp","Klebsiella oxytoca","Klebsiella pneumonia","Klebsiella sp","Listeria monocytogenes","Neisseria meningitidis","Outras leveduras","Outros bacilos gram positivos","Outros bacilos Gram-negativo","Outros cocos gram negativos","Outros cocos gram positivos","Outros Enterococcus","Outros fungos filamentosos","Outros patógenos","Outros Staphylococcus","Outros Streptococcus","Pneumocystis jirovecci","Pseudomonas aeruginosa","Pseudomonas sp","Staphylococcus aureus","Streptococcus pneumoniae","Nenhum")
levels(data$urp1s1_dd___1)=c("Unchecked","Checked")
levels(data$urp1s1_dd___2)=c("Unchecked","Checked")
levels(data$urp1s1_dd___3)=c("Unchecked","Checked")
levels(data$urp1s2_dd___2)=c("Unchecked","Checked")
levels(data$urp1s2_dd___3)=c("Unchecked","Checked")
levels(data$urp1s3_dd___1)=c("Unchecked","Checked")
levels(data$urp1s3_dd___2)=c("Unchecked","Checked")
levels(data$urp1s3_dd___3)=c("Unchecked","Checked")
levels(data$urp1s3_dd___4)=c("Unchecked","Checked")
levels(data$urp2_dd)=c("Acinetobacter baumannii","Acinetobacter sp","Aspergillus","Candida albicans","Candida glabrata","Candida kruzei","Candida sp","Clostridium SP","Enterococcus faecalis","Enterococcus faecium","Escherichia coli","Escherichia sp","Fusarium","Haemophilus influenzae","Haemophilus sp","Klebsiella oxytoca","Klebsiella pneumonia","Klebsiella sp","Listeria monocytogenes","Neisseria meningitidis","Outras leveduras","Outros bacilos gram positivos","Outros bacilos Gram-negativo","Outros cocos gram negativos","Outros cocos gram positivos","Outros Enterococcus","Outros fungos filamentosos","Outros patógenos","Outros Staphylococcus","Outros Streptococcus","Pneumocystis jirovecci","Pseudomonas aeruginosa","Pseudomonas sp","Staphylococcus aureus","Streptococcus pneumoniae","Nenhum")
levels(data$urp2s1_dd___1)=c("Unchecked","Checked")
levels(data$urp2s1_dd___2)=c("Unchecked","Checked")
levels(data$urp2s1_dd___3)=c("Unchecked","Checked")
levels(data$urp2s2_dd___2)=c("Unchecked","Checked")
levels(data$urp2s2_dd___3)=c("Unchecked","Checked")
levels(data$urp2s3_dd___1)=c("Unchecked","Checked")
levels(data$urp2s3_dd___2)=c("Unchecked","Checked")
levels(data$urp2s3_dd___3)=c("Unchecked","Checked")
levels(data$urp2s3_dd___4)=c("Unchecked","Checked")
levels(data$colcatet_dd)=c("Sim","Não")
levels(data$pcp1_dd)=c("Acinetobacter baumannii","Acinetobacter sp","Aspergillus","Candida albicans","Candida glabrata","Candida kruzei","Candida sp","Clostridium SP","Enterococcus faecalis","Enterococcus faecium","Escherichia coli","Escherichia sp","Fusarium","Haemophilus influenzae","Haemophilus sp","Klebsiella oxytoca","Klebsiella pneumonia","Klebsiella sp","Listeria monocytogenes","Neisseria meningitidis","Outras leveduras","Outros bacilos gram positivos","Outros bacilos Gram-negativo","Outros cocos gram negativos","Outros cocos gram positivos","Outros Enterococcus","Outros fungos filamentosos","Outros patógenos","Outros Staphylococcus","Outros Streptococcus","Pneumocystis jirovecci","Pseudomonas aeruginosa","Pseudomonas sp","Staphylococcus aureus","Streptococcus pneumoniae","Nenhum")
levels(data$pcp1s1_dd___1)=c("Unchecked","Checked")
levels(data$pcp1s1_dd___2)=c("Unchecked","Checked")
levels(data$pcp1s1_dd___3)=c("Unchecked","Checked")
levels(data$pcp1s2_dd___2)=c("Unchecked","Checked")
levels(data$pcp1s2_dd___3)=c("Unchecked","Checked")
levels(data$pcp1s3_dd___1)=c("Unchecked","Checked")
levels(data$pcp1s3_dd___2)=c("Unchecked","Checked")
levels(data$pcp1s3_dd___3)=c("Unchecked","Checked")
levels(data$pcp1s3_dd___4)=c("Unchecked","Checked")
levels(data$pcp2_dd)=c("Acinetobacter baumannii","Acinetobacter sp","Aspergillus","Candida albicans","Candida glabrata","Candida kruzei","Candida sp","Clostridium SP","Enterococcus faecalis","Enterococcus faecium","Escherichia coli","Escherichia sp","Fusarium","Haemophilus influenzae","Haemophilus sp","Klebsiella oxytoca","Klebsiella pneumonia","Klebsiella sp","Listeria monocytogenes","Neisseria meningitidis","Outras leveduras","Outros bacilos gram positivos","Outros bacilos Gram-negativo","Outros cocos gram negativos","Outros cocos gram positivos","Outros Enterococcus","Outros fungos filamentosos","Outros patógenos","Outros Staphylococcus","Outros Streptococcus","Pneumocystis jirovecci","Pseudomonas aeruginosa","Pseudomonas sp","Staphylococcus aureus","Streptococcus pneumoniae","Nenhum")
levels(data$pcp2s1_dd___1)=c("Unchecked","Checked")
levels(data$pcp2s1_dd___2)=c("Unchecked","Checked")
levels(data$pcp2s1_dd___3)=c("Unchecked","Checked")
levels(data$pcp2s2_dd___2)=c("Unchecked","Checked")
levels(data$pcp2s2_dd___3)=c("Unchecked","Checked")
levels(data$pcp2s3_dd___1)=c("Unchecked","Checked")
levels(data$pcp2s3_dd___2)=c("Unchecked","Checked")
levels(data$pcp2s3_dd___3)=c("Unchecked","Checked")
levels(data$pcp2s3_dd___4)=c("Unchecked","Checked")
levels(data$colbronco_dd)=c("Sim","Não")
levels(data$lbp1_dd)=c("Acinetobacter baumannii","Acinetobacter sp","Aspergillus","Candida albicans","Candida glabrata","Candida kruzei","Candida sp","Clostridium SP","Enterococcus faecalis","Enterococcus faecium","Escherichia coli","Escherichia sp","Fusarium","Haemophilus influenzae","Haemophilus sp","Klebsiella oxytoca","Klebsiella pneumonia","Klebsiella sp","Listeria monocytogenes","Neisseria meningitidis","Outras leveduras","Outros bacilos gram positivos","Outros bacilos Gram-negativo","Outros cocos gram negativos","Outros cocos gram positivos","Outros Enterococcus","Outros fungos filamentosos","Outros patógenos","Outros Staphylococcus","Outros Streptococcus","Pneumocystis jirovecci","Pseudomonas aeruginosa","Pseudomonas sp","Staphylococcus aureus","Streptococcus pneumoniae","Nenhum")
levels(data$lbp1s1_dd___1)=c("Unchecked","Checked")
levels(data$lbp1s1_dd___2)=c("Unchecked","Checked")
levels(data$lbp1s1_dd___3)=c("Unchecked","Checked")
levels(data$lbp1s2_dd___2)=c("Unchecked","Checked")
levels(data$lbp1s2_dd___3)=c("Unchecked","Checked")
levels(data$lbp1s3_dd___1)=c("Unchecked","Checked")
levels(data$lbp1s3_dd___2)=c("Unchecked","Checked")
levels(data$lbp1s3_dd___3)=c("Unchecked","Checked")
levels(data$lbp1s3_dd___4)=c("Unchecked","Checked")
levels(data$lbp2_dd)=c("Acinetobacter baumannii","Acinetobacter sp","Aspergillus","Candida albicans","Candida glabrata","Candida kruzei","Candida sp","Clostridium SP","Enterococcus faecalis","Enterococcus faecium","Escherichia coli","Escherichia sp","Fusarium","Haemophilus influenzae","Haemophilus sp","Klebsiella oxytoca","Klebsiella pneumonia","Klebsiella sp","Listeria monocytogenes","Neisseria meningitidis","Outras leveduras","Outros bacilos gram positivos","Outros bacilos Gram-negativo","Outros cocos gram negativos","Outros cocos gram positivos","Outros Enterococcus","Outros fungos filamentosos","Outros patógenos","Outros Staphylococcus","Outros Streptococcus","Pneumocystis jirovecci","Pseudomonas aeruginosa","Pseudomonas sp","Staphylococcus aureus","Streptococcus pneumoniae","Nenhum")
levels(data$lbp2s1_dd___1)=c("Unchecked","Checked")
levels(data$lbp2s1_dd___2)=c("Unchecked","Checked")
levels(data$lbp2s1_dd___3)=c("Unchecked","Checked")
levels(data$lbp2s2_dd___2)=c("Unchecked","Checked")
levels(data$lbp2s2_dd___3)=c("Unchecked","Checked")
levels(data$lbp2s3_dd___1)=c("Unchecked","Checked")
levels(data$lbp2s3_dd___2)=c("Unchecked","Checked")
levels(data$lbp2s3_dd___3)=c("Unchecked","Checked")
levels(data$lbp2s3_dd___4)=c("Unchecked","Checked")
levels(data$colhemoc_dd)=c("Sim","Não")
levels(data$hcp1_dd)=c("Acinetobacter baumannii","Acinetobacter sp","Aspergillus","Candida albicans","Candida glabrata","Candida kruzei","Candida sp","Clostridium SP","Enterococcus faecalis","Enterococcus faecium","Escherichia coli","Escherichia sp","Fusarium","Haemophilus influenzae","Haemophilus sp","Klebsiella oxytoca","Klebsiella pneumonia","Klebsiella sp","Listeria monocytogenes","Neisseria meningitidis","Outras leveduras","Outros bacilos gram positivos","Outros bacilos Gram-negativo","Outros cocos gram negativos","Outros cocos gram positivos","Outros Enterococcus","Outros fungos filamentosos","Outros patógenos","Outros Staphylococcus","Outros Streptococcus","Pneumocystis jirovecci","Pseudomonas aeruginosa","Pseudomonas sp","Staphylococcus aureus","Streptococcus pneumoniae","Nenhum")
levels(data$hcp1s1_dd___1)=c("Unchecked","Checked")
levels(data$hcp1s1_dd___2)=c("Unchecked","Checked")
levels(data$hcp1s1_dd___3)=c("Unchecked","Checked")
levels(data$hcp1s2_dd___2)=c("Unchecked","Checked")
levels(data$hcp1s2_dd___3)=c("Unchecked","Checked")
levels(data$hcp1s3_dd___1)=c("Unchecked","Checked")
levels(data$hcp1s3_dd___2)=c("Unchecked","Checked")
levels(data$hcp1s3_dd___3)=c("Unchecked","Checked")
levels(data$hcp1s3_dd___4)=c("Unchecked","Checked")
levels(data$hcp2_dd)=c("Acinetobacter baumannii","Acinetobacter sp","Aspergillus","Candida albicans","Candida glabrata","Candida kruzei","Candida sp","Clostridium SP","Enterococcus faecalis","Enterococcus faecium","Escherichia coli","Escherichia sp","Fusarium","Haemophilus influenzae","Haemophilus sp","Klebsiella oxytoca","Klebsiella pneumonia","Klebsiella sp","Listeria monocytogenes","Neisseria meningitidis","Outras leveduras","Outros bacilos gram positivos","Outros bacilos Gram-negativo","Outros cocos gram negativos","Outros cocos gram positivos","Outros Enterococcus","Outros fungos filamentosos","Outros patógenos","Outros Staphylococcus","Outros Streptococcus","Pneumocystis jirovecci","Pseudomonas aeruginosa","Pseudomonas sp","Staphylococcus aureus","Streptococcus pneumoniae","Nenhum")
levels(data$hcp2s1_dd___1)=c("Unchecked","Checked")
levels(data$hcp2s1_dd___2)=c("Unchecked","Checked")
levels(data$hcp2s1_dd___3)=c("Unchecked","Checked")
levels(data$hcp2s2_dd___2)=c("Unchecked","Checked")
levels(data$hcp2s2_dd___3)=c("Unchecked","Checked")
levels(data$hcp2s3_dd___1)=c("Unchecked","Checked")
levels(data$hcp2s3_dd___2)=c("Unchecked","Checked")
levels(data$hcp2s3_dd___3)=c("Unchecked","Checked")
levels(data$hcp2s3_dd___4)=c("Unchecked","Checked")
levels(data$colpunc_dd)=c("Sim","Não")
levels(data$plp1_dd)=c("Acinetobacter baumannii","Acinetobacter sp","Aspergillus","Candida albicans","Candida glabrata","Candida kruzei","Candida sp","Clostridium SP","Enterococcus faecalis","Enterococcus faecium","Escherichia coli","Escherichia sp","Fusarium","Haemophilus influenzae","Haemophilus sp","Klebsiella oxytoca","Klebsiella pneumonia","Klebsiella sp","Listeria monocytogenes","Neisseria meningitidis","Outras leveduras","Outros bacilos gram positivos","Outros bacilos Gram-negativo","Outros cocos gram negativos","Outros cocos gram positivos","Outros Enterococcus","Outros fungos filamentosos","Outros patógenos","Outros Staphylococcus","Outros Streptococcus","Pneumocystis jirovecci","Pseudomonas aeruginosa","Pseudomonas sp","Staphylococcus aureus","Streptococcus pneumoniae","Nenhum")
levels(data$plp1s1_dd___1)=c("Unchecked","Checked")
levels(data$plp1s1_dd___2)=c("Unchecked","Checked")
levels(data$plp1s1_dd___3)=c("Unchecked","Checked")
levels(data$plp1s2_dd___2)=c("Unchecked","Checked")
levels(data$plp1s2_dd___3)=c("Unchecked","Checked")
levels(data$plp1s3_dd___1)=c("Unchecked","Checked")
levels(data$plp1s3_dd___2)=c("Unchecked","Checked")
levels(data$plp1s3_dd___3)=c("Unchecked","Checked")
levels(data$plp1s3_dd___4)=c("Unchecked","Checked")
levels(data$plp2_dd)=c("Acinetobacter baumannii","Acinetobacter sp","Aspergillus","Candida albicans","Candida glabrata","Candida kruzei","Candida sp","Clostridium SP","Enterococcus faecalis","Enterococcus faecium","Escherichia coli","Escherichia sp","Fusarium","Haemophilus influenzae","Haemophilus sp","Klebsiella oxytoca","Klebsiella pneumonia","Klebsiella sp","Listeria monocytogenes","Neisseria meningitidis","Outras leveduras","Outros bacilos gram positivos","Outros bacilos Gram-negativo","Outros cocos gram negativos","Outros cocos gram positivos","Outros Enterococcus","Outros fungos filamentosos","Outros patógenos","Outros Staphylococcus","Outros Streptococcus","Pneumocystis jirovecci","Pseudomonas aeruginosa","Pseudomonas sp","Staphylococcus aureus","Streptococcus pneumoniae","Nenhum")
levels(data$plp2s1_dd___1)=c("Unchecked","Checked")
levels(data$plp2s1_dd___2)=c("Unchecked","Checked")
levels(data$plp2s1_dd___3)=c("Unchecked","Checked")
levels(data$plp2s2_dd___2)=c("Unchecked","Checked")
levels(data$plp2s2_dd___3)=c("Unchecked","Checked")
levels(data$plp2s3_dd___1)=c("Unchecked","Checked")
levels(data$plp2s3_dd___2)=c("Unchecked","Checked")
levels(data$plp2s3_dd___3)=c("Unchecked","Checked")
levels(data$plp2s3_dd___4)=c("Unchecked","Checked")
levels(data$dados_dirios_716778_complete)=c("Incomplete","Unverified","Complete")
levels(data$statalta_ah)=c("Vivo","Óbito")
levels(data$alta_ah)=c("Casa","Casa de repouso","Hospital de retaguarda","Outro hospital")
levels(data$limressu_ah)=c("Sim","Não")
levels(data$limadsu_ah)=c("Sim","Não")
levels(data$limretsu_ah)=c("Sim","Não")
levels(data$dcorpo_ah)=c("Entregue à família","SVO","IML")